CREATE DATABASE capstone;
\c capstone;


CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL UNIQUE,
  country TEXT NOT NULL,
  birthdate INTEGER NULL DEFAULT NULL,
  lastlogin INTEGER NOT NULL,
  isartist BOOLEAN DEFAULT FALSE,
  ispremium BOOLEAN DEFAULT FALSE,
  image TEXT NULL DEFAULT NULL
);